In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.read_csv('diabetes.csv')

In [8]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [12]:
#to find out if there are any null (NAN) values
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [10]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [21]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [18]:
#to check if there is imbalace in output
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [36]:
268/500

0.536

In [22]:
X=df.drop(['Outcome'],axis=1)
y=df['Outcome']

In [19]:
#scaling the data
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [23]:
X_scaled=scaler.fit_transform(X)

In [24]:
X_scaled

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

### we will get 2d arrays of the scaled values we could also use StandarScaler for the scaling purpose

In [25]:
from sklearn.model_selection import train_test_split 

In [28]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,random_state=10,stratify=y)

### Stratify=y will maintain the the proportion of the outcomes while spliting the data into train and test data

In [30]:
len(X_test)/len(X_train)

0.3333333333333333

In [34]:
y_train.value_counts()


Outcome
0    375
1    201
Name: count, dtype: int64

In [37]:
201/375
#the proportion of the outcomes in the train dataset is mantianed as in the whole data

0.536

In [40]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [43]:
scores=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores

array([0.69480519, 0.66233766, 0.72727273, 0.78431373, 0.7254902 ])

In [44]:
scores.mean()

0.7188439011968424

In [51]:
from sklearn.ensemble import BaggingClassifier
bagged=BaggingClassifier(
    base_estimator= DecisionTreeClassifier(), #we are choosing DecisioinTreeClassifier as the model
    n_estimators=100, #we are creating 100 different random samples
    max_samples=0.8, # the size of the each sample will be 80% of the training data
    oob_score=True, # oob('out of bag') this are the data that were not included in any of the samples 
                   #they will be used as test data to predict the accuracy. the accuracy calculated from 
                   #this testing data is called obb_score 
    random_state=0
    
)
bagged.fit(X_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(), max_samples=0.8,
                  n_estimators=100, oob_score=True, random_state=0)

In [56]:
bagged.oob_score_

0.7586805555555556

In [58]:
bagged.score(X_test,y_test)

0.7760416666666666

In [60]:
bagged_score=cross_val_score(bagged,X,y ,cv=5)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/

In [61]:
bagged_score

array([0.75324675, 0.72727273, 0.74675325, 0.82352941, 0.73856209])

In [62]:
bagged_score.mean()

0.7578728461081402