In [45]:
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import svm ,datasets
import numpy as np

In [46]:
iris=datasets.load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target
df['flower']=df.flower.apply(lambda x: iris.target_names[x])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

        flower  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [47]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(['flower'],axis=1),iris.target)

In [48]:
from sklearn.model_selection import cross_val_score
score=cross_val_score(svm.SVC(gamma='auto',kernel='linear',C=10),iris.data,iris.target,cv=5)
score

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [49]:
score=cross_val_score(svm.SVC(gamma='auto',kernel='linear',C=20),iris.data,iris.target,cv=5)
score

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [50]:
score=cross_val_score(svm.SVC(gamma='auto',kernel='linear',C=30),iris.data,iris.target,cv=5)
score

array([1. , 1. , 0.9, 0.9, 1. ])

we can use a for loop to repeat the process for various value of the parameter 

In [51]:
kernel=['rbf','linear','poly']
C=[10,20,30]
avg_score={}
for krn in kernel:
    for c_val in C:
        cv_score=cross_val_score(svm.SVC(gamma='auto',C=c_val,kernel=krn),iris.data,iris.target,cv=5)
        avg_score[krn +'_' + str(c_val)] = np.mean(cv_score)
print(avg_score)



{'rbf_10': 0.9800000000000001, 'rbf_20': 0.9666666666666668, 'rbf_30': 0.96, 'linear_10': 0.9733333333333334, 'linear_20': 0.9666666666666666, 'linear_30': 0.96, 'poly_10': 0.9666666666666666, 'poly_20': 0.9533333333333334, 'poly_30': 0.9533333333333334}


In [52]:
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'kernel' : ['rbf','linear','poly'],
    'C':[10,20,30]
},cv=5,return_train_score=False)

In [53]:
clf.fit(iris.data,iris.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [10, 20, 30],
                         'kernel': ['rbf', 'linear', 'poly']})

In [54]:
results=pd.DataFrame(clf.cv_results_)

In [55]:
results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.000984      0.000207         0.000634        0.000120      10   
1       0.000793      0.000054         0.000554        0.000070      10   
2       0.003721      0.002349         0.000323        0.000036      10   
3       0.000428      0.000052         0.000250        0.000020      20   
4       0.000331      0.000012         0.000206        0.000003      20   
5       0.005191      0.004746         0.000219        0.000036      20   
6       0.000314      0.000034         0.000189        0.000014      30   
7       0.000249      0.000007         0.000148        0.000005      30   
8       0.004114      0.003442         0.000134        0.000007      30   

  param_kernel                         params  split0_test_score  \
0          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
1       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
2         poly    {'C': 10, 'kernel': 'poly'}           1.000000   
3          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
4       linear  {'C': 20, 'kernel': 'linear'}           1.000000   
5         poly    {'C': 20, 'kernel': 'poly'}           0.966667   
6          rbf     {'C': 30, 'kernel': 'rbf'}           0.966667   
7       linear  {'C': 30, 'kernel': 'linear'}           1.000000   
8         poly    {'C': 30, 'kernel': 'poly'}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           0.966667           0.966667                1.0   
1           1.000000           0.900000           0.966667                1.0   
2           1.000000           0.900000           0.933333                1.0   
3           1.000000           0.900000           0.966667                1.0   
4           1.000000           0.900000           0.933333                1.0   
5           0.966667           0.900000           0.933333                1.0   
6           1.000000           0.900000           0.933333                1.0   
7           1.000000           0.900000           0.900000                1.0   
8           0.966667           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.973333        0.038873                2  
2         0.966667        0.042164                4  
3         0.966667        0.036515                3  
4         0.966667        0.042164                4  
5         0.953333        0.033993                8  
6         0.960000        0.038873                6  
7         0.960000        0.048990                6  
8         0.953333        0.033993                8

In [56]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'inverse_transform',
 'multimetric_',
 'n_fe

In [57]:
clf.best_score_

0.9800000000000001

In [58]:
clf.best_params_

{'C': 10, 'kernel': 'rbf'}

In [59]:
from sklearn.model_selection import RandomizedSearchCV
clfr=RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':range(1,10),
    'kernel':['rbf','poly','linear']
},cv=5,return_train_score=False,n_iter=2)

In [60]:
clfr.fit(iris.data,iris.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': range(1, 10),
                                        'kernel': ['rbf', 'poly', 'linear']})

In [61]:
clfr_df=pd.DataFrame(clfr.cv_results_)

In [62]:
clfr_df[['param_kernel','param_C','mean_test_score']]

param_kernel param_C  mean_test_score
0         poly       3         0.966667
1       linear       1         0.980000

In [63]:
import joblib

In [68]:
joblib.dump(clfr,'RandomizedSearchCV')

['RandomizedSearchCV']

In [69]:
joblib.dump(clf,'GridSearchCV')

['GridSearchCV']